Lifting style
Kozea/www-kozea pull request #143
Opened 2021-11-02 09:25 UTC by annabellou

J'ouvre cette pull request pour merger les premiers ajustements de style du site concernant les tickets suivants : 

- https://github.com/Kozea/kozea/issues/2057
- https://github.com/Kozea/kozea/issues/2051

2021-11-19 16:04 UTC, gentooboontoo requested changes
J'ai fini la revue :sweat_smile: Good job :slightly_smiling_face: (juste quelques petits trucs mineurs à changer)

2021-11-22 10:45 UTC, annabellou commented on www_kozea/templates/backoffice.html
> +    <div class="product-banner--dark--container">
Oui c'est vrai, d'autant que ses voisins s'appellent `product-banner__descriptive` et `product-banner__illustrative`. Du coup j'ai renommé les class dans les fichiers html des pages solutions et j'ai changé le nom de la class dans le fichier .sass.

2021-11-22 10:45 UTC, annabellou commented on www_kozea/static/sass/style.scss
> +    z-index: 9;
Merci !

2021-11-22 10:48 UTC, annabellou commented on www_kozea/static/sass/style.scss
> +    // padding: 2em;
Oupsi… 😅 il est bien supprimé cette fois !

2021-11-22 10:57 UTC, gentooboontoo approved these changes
:+1:

2021-11-23 09:13 UTC, merged